### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by wgp666** [hongyaohongyao/smart_classroom_demo#19]
大佬，我配好这个环境运行代码的时候报错
Traceback (most recent call last):
  File "D:/下载/smart_classroom_demo-master/smart_classroom_demo-master/smart_classroom_app.py", line 7, in <module>
    from smart_classroom.dynamic_attendance_app import DynamicAttendanceApp
  File "D:\下载\smart_classroom_demo-master\smart_classroom_demo-master\smart_classroom\dynamic_attendance_app.py", line 15, in <module>
    from pipeline_module.face_detection_module import FaceDetectionModule
  File "D:\下载\smart_classroom_demo-master\smart_classroom_demo-master\pipeline_module\face_detection_module.py", line 3, in <module>
    from face_recog.models import face_recog
  File "D:\下载\smart_classroom_demo-master\smart_classroom_demo-master\face_recog\models\face_recog.py", line 9, in <module>
    pose_predictor_68_point = dlib.shape_predictor(predictor_68_point_model)
RuntimeError: Unable to open D:\下载\smart_classroom_demo-master\smart_classroom_demo-master\weights\shape_predictor_68_face_landmarks.dat
你知道是什么原因吗？

**Comment by hongyaohongyao** [comment]
别用中文路径

**Comment by wgp666** [comment]
好的，解决了，感谢大佬
