### ISSUE TITLE
代码，环境问题！

### ISSUE THREAD

**Issue by Kidgod77** [hongyaohongyao/smart_classroom_demo#36]
您好，请问一下dlib必须用gpu的才可以吗？如果是的话，您方便提供一下您编译好的dlib包吗，看网上的教程一直搞不成，或者如果是因为有一些代码的改动的话，您方便发我一份完整的程序压缩包吗？我是一名在校生，最近想做一个活体检测的项目，希望得到您的一些帮助，有偿请您抽空帮忙指导一下，调试一下这个项目的环境，一定达到您的满意，感激不尽，我的邮箱是374197975@qq.com,希望能得到您的回复！

**Comment by Kidgod77** [comment]
dlib编译好了，但是动态点名那里打不开摄像头，会报错。注册的界面可以识别人脸，但是不会进行注册，进度没变化。。所有的环境都和您的一样。下面贴一下动态点名的报错


Exception in thread Thread-12:
Traceback (most recent call last):
  File "D:\Anaconda\envs\face\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\envs\face\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\recover code\recover code\smart_classroom_demo-master\pipeline_module\core\base_module.py", line 102, in _run
    execute_result = self.process_data(task_data.data) if execute_condition else task_data.task_flag
  File "D:\recover code\recover code\smart_classroom_demo-master\pipeline_module\face_match_module.py", line 22, in process_data
    raw_face_labels = np.argmin(face_distances, axis=1) if face_distances.shape[0] > 0 else np.array([])
  File "<__array_function__ internals>", line 5, in argmin
  File "D:\Anaconda\envs\face\lib\site-packages\numpy\core\fromnumeric.py", line 1276, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "D:\Anaconda\envs\face\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
