### ISSUE TITLE
这个错误怎么解决  安装都是失败

### ISSUE THREAD

**Issue by Hackfreedom888** [hongyaohongyao/smart_classroom_demo#40]
Traceback (most recent call last):
  File "smart_classroom_app.py", line 7, in <module>
    from smart_classroom.dynamic_attendance_app import DynamicAttendanceApp
  File "C:\Users\xudaojin\smart_classroom_demo\smart_classroom\dynamic_attendance_app.py", line 15, in <module>
    from pipeline_module.face_detection_module import FaceDetectionModule
  File "C:\Users\xudaojin\smart_classroom_demo\pipeline_module\face_detection_module.py", line 3, in <module>
    from face_recog.models import face_recog
  File "C:\Users\xudaojin\smart_classroom_demo\face_recog\models\face_recog.py", line 2, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'

**Comment by hongyaohongyao** [comment]
安装gpu版的dlib https://blog.csdn.net/qq_38361589/article/details/124983127
