### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by whendoomsday** [hongyaohongyao/smart_classroom_demo#47]
为什么运行之后点击摄像头没有反应呢

**Comment by DSLYL** [comment]
是不是环境没有配置好呢  
你点击本地视频有反应吗

**Comment by ephhz** [comment]
同问，点击摄像头只显示loading，本地视频报错模型维度不匹配

**Comment by zhangchufeng** [comment]
同问，专注度分析一直都是timer，播放本地视频直接闪退，其他的都正常

**Comment by ZiFengHuang0520** [comment]
> 同问，点击摄像头只显示loading，本地视频报错模型维度不匹配

视频报错模型维度不匹配怎么解决

**Comment by LYJJYL** [comment]
> 是不是环境没有配置好呢 你点击本地视频有反应吗

你好有问题联系您，可以加一下qq2417642972详谈吗

**Comment by DIF123BUG** [comment]
> 同问，点击摄像头只显示loading，本地视频报错模型维度不匹配

请问你解决了吗

**Comment by DIF123BUG** [comment]
> > 同问，点击摄像头只显示loading，本地视频报错模型维度不匹配
> 
> 视频报错模型维度不匹配怎么解决
请问已解决了嘛

**Comment by DSLYL** [comment]
你好，这个的话，是因为视频大小限制的，博主的视频大小目前那个只能运行640×480 和800×480的本地视频&nbsp;
你可以裁剪录屏这样一个视频就行啦


1150475496
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hongyaohongyao/smart_classroom_demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 中午11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hongyaohongyao/smart_classroom_demo] 求助 (Issue #47)





   
同问，点击摄像头只显示loading，本地视频报错模型维度不匹配
  
视频报错模型维度不匹配怎么解决
 请问已解决了嘛

**Comment by DIF123BUG** [comment]
谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月5日(周三) 上午9:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hongyaohongyao/smart_classroom_demo] 求助 (Issue #47)




 你好，这个的话，是因为视频大小限制的，博主的视频大小目前那个只能运行640×480 和800×480的本地视频&amp;nbsp; 
 你可以裁剪录屏这样一个视频就行啦 
 
 
 1150475496 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "hongyaohongyao/smart_classroom_demo"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年5月14日(星期二) 中午11:28 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [hongyaohongyao/smart_classroom_demo] 求助 (Issue #47) 
 
 
 
 
 
     
 同问，点击摄像头只显示loading，本地视频报错模型维度不匹配 
    
 视频报错模型维度不匹配怎么解决 
  请问已解决了嘛

**Comment by XXsxxxx** [comment]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\d2l\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "D:\ProgramData\anaconda3\envs\d2l\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "E:\smart_classroom_demo-master\pipeline_module\core\base_module.py", line 102, in _run
    execute_result = self.process_data(task_data.data) if execute_condition else task_data.task_flag
  File "E:\smart_classroom_demo-master\pipeline_module\vis_modules.py", line 167, in process_data
    self.draw_frame(data, fps=fps)
  File "E:\smart_classroom_demo-master\pipeline_module\vis_modules.py", line 221, in draw_frame
    draw_frame(data, fps=fps)
  File "E:\smart_classroom_demo-master\pipeline_module\vis_modules.py", line 53, in draw_frame
    data.draw_axis(frame, r, t)
  File "E:\smart_classroom_demo-master\models\pose_estimator.py", line 384, in draw_axis
    cv2.line(img, tuple(axisPoints[3].ravel()), tuple(
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - img marked as output argument, but provided NumPy array marked as readonly
>  - Expected Ptr<cv::UMat> for argument 'img'
这是什么问题呀
